input-output-hk/thorn-calculus

.github/workflows/quick-and-dirty-build.yaml
src/ROOT
src/Thorn_Calculus-Actions.thy
src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Foundations.thy
src/Thorn_Calculus-Processes.thy
src/Thorn_Calculus-Semantics-Asynchronous.thy
src/Thorn_Calculus-Semantics-Synchronous.thy
src/binder_preservation.ML
src/document/root.tex

Move the current version of the software into this repository

---

src/Thorn_Calculus-Semantics-Synchronous.thy

Finalize the switching over to the next-generation equivalence reasoner

---

LICENSE.md

Switch to Apache 2.0 license

---

src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Processes.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Add support for repeated receiving

---

src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Start using shortcut for `receive` follow-ups

---

src/Thorn_Calculus-Core_Bisimilarities.thy

Turn `a` into `b` in `receive_scope_extension`

---

src/Thorn_Calculus-Processes.thy

Stop declaring functions as friends of `corec`

---

src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Generalize `receive_follow_up`

---

src/Thorn_Calculus-Semantics-Synchronous.thy

Add `post_receive_after` lemmas

---

src/Thorn_Calculus-Semantics-Synchronous.thy

Rename `universe` `synchronous_universe`

---

src/Thorn_Calculus-Foundations.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Generalize `dependent_on_chan_at`

---

src/Thorn_Calculus-Semantics-Synchronous.thy

Add support for `receive` quasi-mutation

---

src/Thorn_Calculus-Core_Bisimilarities.thy

Correct order of rewrite rules

---

src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Introduce locale for capturing `∼⇩s`/`≈⇩s`-commonalities

---

src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Processes.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

This will ultimately resolve #15.

Add missing proofs of properties of repeated receiving

---

src/Thorn_Calculus-Semantics-Synchronous.thy

Remove superfluous qualification

---

src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Improve the `transition_from_repeated_receive` statement

---

src/Thorn_Calculus-Core_Bisimilarities.thy

Improve naming in `inner_repeated_receive_redundancy`

---

src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Add `repeated_receive_transition`

---

src/Thorn_Calculus-Core_Bisimilarities.thy

Stop overanalyzing transitions from `repeated_receive`

---

src/Thorn_Calculus-Foundations.thy

Fix typo in `Foundations`

---

src/Thorn_Calculus-Foundations.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Fix spacing

---

src/Thorn_Calculus-Foundations.thy

Simplify the proof of `chan_family_distinctness`

---

src/Thorn_Calculus-Examples.thy

Port `Thorn_Calculus-Experiments` from legacy repository

---

src/Thorn_Calculus-Semantics-Synchronous.thy

Add no-mobility versions of transition system rules

---

src/Thorn_Calculus-Processes.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Add `family_uncurry_after_` lemmas for derived constructs

---

src/Thorn_Calculus-Actions.thy
src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Semantics-Asynchronous.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Change the notation for I/O actions

---

.github/workflows/quick-and-dirty-build.yaml
src/ROOT
src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Foundations.thy
src/Thorn_Calculus-Processes.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

This will ultimately resolve #78.

Add an application layer to the Þ-calculus

---

src/Thorn_Calculus-Foundations.thy

Remove `source_curry_after_move_adapted` reproving

---

src/Thorn_Calculus-Foundations.thy

Make proof of `not_dependent_on_chan_at` clearer

---

src/Thorn_Calculus-Foundations.thy
src/Thorn_Calculus-Processes.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Make some minor improvements

---

src/Thorn_Calculus-Processes.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Align argument orders of function continuations

---

src/Thorn_Calculus-Processes.thy

Start using the `‖`-notation also in its translation

---

src/Thorn_Calculus-Foundations.thy

Replace `rule HOL.ext` by `standard`

---

src/Thorn_Calculus-Actions.thy
src/Thorn_Calculus-Core_Bisimilarities.thy
src/Thorn_Calculus-Examples.thy
src/Thorn_Calculus-Foundations.thy
src/Thorn_Calculus-Processes.thy
src/Thorn_Calculus-Semantics-Asynchronous.thy
src/Thorn_Calculus-Semantics-Synchronous.thy

Improve the layout of `imports` clauses

---

src/ROOT
src/Thorn_Calculus-Derived-Channels-Synchronous.thy

Add support for synchronous channels

---

src/Thorn_Calculus-Derived-Channels-Synchronous.thy

Improve the definition of `sync_channel`

---

src/Thorn_Calculus-Foundations.thy

Give `val` morphisms more descriptive names

---

src/Thorn_Calculus-Derived-Channels-Synchronous.thy

Add support for untyped synchronous channels

---

src/Thorn_Calculus-Derived-Channels-Synchronous.thy

Make `sync_send` processes pretty-printing blocks

---

src/Thorn_Calculus-Derived-Channels-Synchronous.thy

Restrict the types of `sync_send` and `sync_receive`
